### PR TITLE
Kemal integration

### PR DESCRIPTION
**Pull request by mamantoha**

### CODE REVIEW

**Comment by Sija** [comment]
I'm not sure what this PR is about. AFAIK Kemal integration is done and working (with docs you copied from `integrations/kemal.cr`), Also, _any_hash_ is updated in the `develop` branch, so you can use that.

**Comment by mamantoha** [comment]
@Sija  this PR is about bumping version of `any_hash.cr`. It doesn't work for me with `0.2.1`.

**Comment by emq** [comment]
As mentioned above - `any_hash` was bumped in `develop` branch, but I think `develop` can be master now and it's safely to release new version - I'm running `develop` on my project for quite some time know and can confirm everything works as it should 🙆‍♂️ 💪

**Comment by Sija** [comment]
@emq That's gr8 to hear! I'll do it once I fix the Amber integration, which broke just recently :(

**Comment by mamantoha** [comment]
@Sija yeah everything works. I believe this shard needs more documentation. I spent a few hours while making it work for Heroku :tada:

**Comment by Sija** [comment]
@mamantoha Anything you care to share to help others with it?

**Pull request closed without merging**
