### PR TITLE
crystal 0.29 support

### PR DESCRIPTION
**Pull request by mamantoha**
'!' or '?' at the end of the LHS in an assignment is dissallowed

### CODE REVIEW

**Comment by Sija** [comment]
@mamantoha Please, (change base to, and) rebase this PR on top of `develop` branch.

**Comment by mamantoha** [comment]
Done

**Comment by Sija** [comment]
Please remove changes in `spec/raven/processors/http_headers_spec.cr` since they're unrelated to this PR. Once it's done I'll happily merge it.

**Comment by mamantoha** [comment]
Done

**Comment by Sija** [comment]
Thanks! 🙇‍♂️

**Pull request merged**
